Repository MTVS-Noblesse/Triplay, pull requests merged in 2024-08, with the labels that each got.

#19 Feature | Domain:Clip - service to repository
  .idea/compiler.xml
  backend/build.gradle
  backend/src/main/java/com/noblesse/backend/clip/domain/Clip.java
  backend/src/main/java/com/noblesse/backend/clip/domain/ClipCoComment.java
  backend/src/main/java/com/noblesse/backend/clip/domain/ClipComment.java
  backend/src/main/java/com/noblesse/backend/clip/domain/ClipReport.java
  backend/src/main/java/com/noblesse/backend/clip/dto/ClipCoCommentRegistRequestDTO.java
  backend/src/main/java/com/noblesse/backend/clip/dto/ClipCommentRegistRequestDTO.java
  backend/src/main/java/com/noblesse/backend/clip/dto/ClipRegistRequestDTO.java
  backend/src/main/java/com/noblesse/backend/clip/dto/ClipReportRegistRequestDTO.java
  backend/src/main/java/com/noblesse/backend/clip/repository/ClipCoCommentRepository.java
  backend/src/main/java/com/noblesse/backend/clip/repository/ClipCommentRepository.java
  backend/src/main/java/com/noblesse/backend/clip/repository/ClipReportRepository.java
  backend/src/main/java/com/noblesse/backend/clip/repository/ClipRepository.java
  backend/src/main/java/com/noblesse/backend/clip/service/ClipCoCommentService.java
  backend/src/main/java/com/noblesse/backend/clip/service/ClipCommentService.java
  backend/src/main/java/com/noblesse/backend/clip/service/ClipReportService.java
  backend/src/main/java/com/noblesse/backend/clip/service/ClipService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/ClipMapper.xml
Labels: ✨ Feature

#24 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs

#26 Feat: Post 관련 도메인 조회 기능 구현 완료
  backend/src/main/java/com/noblesse/backend/post/Post.java
  backend/src/main/java/com/noblesse/backend/post/PostCoComment.java
  backend/src/main/java/com/noblesse/backend/post/PostComment.java
  backend/src/main/java/com/noblesse/backend/post/PostReport.java
  backend/src/main/java/com/noblesse/backend/post/api/query/PostCoCommentQueryController.java
  backend/src/main/java/com/noblesse/backend/post/api/query/PostCommentQueryController.java
  backend/src/main/java/com/noblesse/backend/post/api/query/PostQueryController.java
  backend/src/main/java/com/noblesse/backend/post/api/query/PostReportQueryController.java
  backend/src/main/java/com/noblesse/backend/post/common/dto/PostCoCommentDTO.java
  backend/src/main/java/com/noblesse/backend/post/common/dto/PostCommentDTO.java
  backend/src/main/java/com/noblesse/backend/post/common/dto/PostDTO.java
  backend/src/main/java/com/noblesse/backend/post/common/dto/PostReportDTO.java
  backend/src/main/java/com/noblesse/backend/post/common/entity/Post.java
  backend/src/main/java/com/noblesse/backend/post/common/entity/PostCoComment.java
  backend/src/main/java/com/noblesse/backend/post/common/entity/PostComment.java
  backend/src/main/java/com/noblesse/backend/post/common/entity/PostReport.java
  backend/src/main/java/com/noblesse/backend/post/common/exception/PostCoCommentNotFoundException.java
  backend/src/main/java/com/noblesse/backend/post/common/exception/PostCommentNotFoundException.java
  backend/src/main/java/com/noblesse/backend/post/common/exception/PostNotFoundException.java
  backend/src/main/java/com/noblesse/backend/post/common/exception/PostReportNotFoundException.java
  backend/src/main/java/com/noblesse/backend/post/query/application/service/PostQueryService.java
  backend/src/main/java/com/noblesse/backend/post/query/infrastructure/persistence/repository/PostCoCommentRepository.java
  backend/src/main/java/com/noblesse/backend/post/query/infrastructure/persistence/repository/PostCommentRepository.java
  backend/src/main/java/com/noblesse/backend/post/query/infrastructure/persistence/repository/PostReportRepository.java
  backend/src/main/java/com/noblesse/backend/post/query/infrastructure/persistence/repository/PostRepository.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/noblesse/backend/post/PostQueryServiceTest.java
Labels: ✨ Feature, ✅ Test
